(function(){
  'use strict';
  const STORE='familyScentCodeV1';
  const RETENTION_MS=90*24*60*60*1000;
  const SIGNS={ru:['Овен','Телец','Близнецы','Рак','Лев','Дева','Весы','Скорпион','Стрелец','Козерог','Водолей','Рыбы'],ua:['Овен','Телець','Близнюки','Рак','Лев','Діва','Терези','Скорпіон','Стрілець','Козоріг','Водолій','Риби'],en:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],nl:['Ram','Stier','Tweelingen','Kreeft','Leeuw','Maagd','Weegschaal','Schorpioen','Boogschutter','Steenbok','Waterman','Vissen']};
  const ELEMENT=['fire','earth','air','water','fire','earth','air','water','fire','earth','air','water'];
  const COPY={
    ru:{subtitle:'Персональный аромат отношений, рассчитанный по натальным картам и семейной синастрии.',choose:'Выберите формат',modes:{my:['MY SCENT','Мой личный аромат'],child:['CHILD SCENT','Аромат ребёнка для дома'],pair:['PARENT & CHILD','Две карты · одна связь'],family:['FAMILY SCENT','Один аромат семьи']},details:'Данные рождения',help:'Мы программно рассчитываем положения планет. AI не придумывает карту.',roles:{self:'Я',child:'Ребёнок',mother:'Мама',partner:'Папа / партнёр'},name:'Имя',date:'Дата рождения',time:'Точное время',place:'Место рождения',unknown:'Время неизвестно',saved:'Использовать сохранённый профиль',select:'Выберите профиль',cityHint:'Введите минимум 3 буквы и выберите город',cityLoading:'Ищем города…',cityNone:'Город не найден',cityError:'Поиск города временно недоступен',calculate:'СОЗДАТЬ МОЙ АРОМАТ',working:'Рассчитываем карты и семейный аккорд…',required:'Заполните имя, дату, время и выберите город для каждого человека.',future:'Дата рождения не может быть в будущем.',result:'YOUR FAMILY SCENT',top:'Верхние ноты',heart:'Сердце',base:'База',story:'История вашего аромата',basis:'Почему именно эти ноты',composition:'Состав семейного кода',metrics:['Связь Луны','Гармония Венеры','Идентичность Солнца','Баланс стихий','Подпись синастрии'],facts:'Основа расчёта',house:'дом',orderTitle:'Создать персональную свечу',orderText:'Элла получит название, состав и код аромата. Детальные данные рождения в сообщение не добавляются.',aboutLabel:'Расскажите немного о себе и заказе',aboutPlaceholder:'Для кого создаётся свеча, повод, любимые и нежелательные ноты, чувствительность к ароматам, страна доставки…',aboutHint:'Необязательно. Этот текст будет добавлен только в сообщение Элле.',messageTitle:'Заказ Family Scent Code',scentLabel:'Аромат',extraLabel:'О заказчике и пожелания',whatsapp:'Заказать в WhatsApp',email:'Заказать по email',safety:'Рецептура свечи должна быть разработана из предназначенных для свечей fragrance oils с соблюдением актуальных ограничений IFRA. Аромат создаёт атмосферу и не является лечебным средством.',unknownFact:'время неизвестно — Асцендент и дома не использованы',asc:'Асцендент',savedLocal:'Расчёт сохранён на этом устройстве.',noAstro:'Не удалось рассчитать карту. Проверьте данные рождения и выбранный город.',members:'Участники'},
    ua:{subtitle:'Персональний аромат стосунків, розрахований за натальними картами та сімейною синастрією.',choose:'Оберіть формат',modes:{my:['MY SCENT','Мій особистий аромат'],child:['CHILD SCENT','Аромат дитини для дому'],pair:['PARENT & CHILD','Дві карти · один зв’язок'],family:['FAMILY SCENT','Один аромат сім’ї']},details:'Дані народження',help:'Ми програмно розраховуємо положення планет. AI не вигадує карту.',roles:{self:'Я',child:'Дитина',mother:'Мама',partner:'Тато / партнер'},name:'Ім’я',date:'Дата народження',time:'Точний час',place:'Місце народження',unknown:'Час невідомий',saved:'Використати збережений профіль',select:'Оберіть профіль',cityHint:'Введіть щонайменше 3 літери й оберіть місто',cityLoading:'Шукаємо міста…',cityNone:'Місто не знайдено',cityError:'Пошук міста тимчасово недоступний',calculate:'СТВОРИТИ МІЙ АРОМАТ',working:'Розраховуємо карти та сімейний акорд…',required:'Заповніть ім’я, дату, час і оберіть місто для кожної людини.',future:'Дата народження не може бути в майбутньому.',result:'YOUR FAMILY SCENT',top:'Верхні ноти',heart:'Серце',base:'База',story:'Історія вашого аромату',basis:'Чому саме ці ноти',composition:'Склад сімейного коду',metrics:['Зв’язок Місяця','Гармонія Венери','Ідентичність Сонця','Баланс стихій','Підпис синастрії'],facts:'Основа розрахунку',house:'дім',orderTitle:'Створити персональну свічку',orderText:'Елла отримає назву, склад і код аромату. Детальні дані народження у повідомлення не додаються.',aboutLabel:'Розкажіть трохи про себе та замовлення',aboutPlaceholder:'Для кого створюється свічка, нагода, улюблені й небажані ноти, чутливість до ароматів, країна доставки…',aboutHint:'Необов’язково. Цей текст буде додано лише до повідомлення Еллі.',messageTitle:'Замовлення Family Scent Code',scentLabel:'Аромат',extraLabel:'Про замовника та побажання',whatsapp:'Замовити у WhatsApp',email:'Замовити через email',safety:'Рецептуру свічки слід розробляти з fragrance oils для свічок із дотриманням актуальних обмежень IFRA. Аромат створює атмосферу й не є лікувальним засобом.',unknownFact:'час невідомий — Асцендент і будинки не використані',asc:'Асцендент',savedLocal:'Розрахунок збережено на цьому пристрої.',noAstro:'Не вдалося розрахувати карту. Перевірте дані й обране місто.',members:'Учасники'},
    en:{subtitle:'A personal scent of relationships, calculated from birth charts and family synastry.',choose:'Choose a format',modes:{my:['MY SCENT','My personal scent'],child:['CHILD SCENT','A child-inspired home scent'],pair:['PARENT & CHILD','Two charts · one bond'],family:['FAMILY SCENT','One shared family scent']},details:'Birth details',help:'Planetary positions are calculated programmatically. AI does not invent the chart.',roles:{self:'Me',child:'Child',mother:'Mother',partner:'Father / partner'},name:'Name',date:'Birth date',time:'Exact time',place:'Birth place',unknown:'Time unknown',saved:'Use saved profile',select:'Select a profile',cityHint:'Enter at least 3 letters and choose a city',cityLoading:'Searching for cities…',cityNone:'City not found',cityError:'City search is temporarily unavailable',calculate:'CREATE MY SCENT',working:'Calculating charts and the shared accord…',required:'Complete the name, date, time and selected city for every person.',future:'Birth date cannot be in the future.',result:'YOUR FAMILY SCENT',top:'Top notes',heart:'Heart',base:'Base',story:'Your scent story',basis:'Why these notes',composition:'Family composition',metrics:['Moon connection','Venus harmony','Sun identity','Element balance','Synastry signature'],facts:'Calculation basis',house:'house',orderTitle:'Create your personal candle',orderText:'Ella will receive the scent name, composition and code. Detailed birth data is not included in the message.',aboutLabel:'Tell us a little about you and your order',aboutPlaceholder:'Who the candle is for, the occasion, notes you love or dislike, scent sensitivity, delivery country…',aboutHint:'Optional. This text will only be added to your message to Ella.',messageTitle:'Family Scent Code order',scentLabel:'Scent',extraLabel:'About the customer and preferences',whatsapp:'Order on WhatsApp',email:'Order by email',safety:'The candle formula should use candle-safe fragrance oils within current IFRA limits. The scent creates atmosphere and is not a treatment or health product.',unknownFact:'time unknown — Ascendant and houses were omitted',asc:'Ascendant',savedLocal:'The calculation is saved on this device.',noAstro:'The chart could not be calculated. Check the birth details and selected city.',members:'Members'},
    nl:{subtitle:'Een persoonlijke geur van relaties, berekend uit geboortehoroscopen en familiesynastrie.',choose:'Kies een vorm',modes:{my:['MY SCENT','Mijn persoonlijke geur'],child:['CHILD SCENT','Een kind-geïnspireerde huisgeur'],pair:['PARENT & CHILD','Twee horoscopen · één band'],family:['FAMILY SCENT','Eén gezamenlijke familiegeur']},details:'Geboortegegevens',help:'Planeetstanden worden programmatisch berekend. AI verzint de horoscoop niet.',roles:{self:'Ik',child:'Kind',mother:'Moeder',partner:'Vader / partner'},name:'Naam',date:'Geboortedatum',time:'Exacte tijd',place:'Geboorteplaats',unknown:'Tijd onbekend',saved:'Gebruik opgeslagen profiel',select:'Kies een profiel',cityHint:'Vul minimaal 3 letters in en kies een plaats',cityLoading:'Plaatsen zoeken…',cityNone:'Plaats niet gevonden',cityError:'Plaats zoeken is tijdelijk niet beschikbaar',calculate:'MAAK MIJN GEUR',working:'Horoscopen en gezamenlijk akkoord berekenen…',required:'Vul voor iedereen naam, datum, tijd en een gekozen plaats in.',future:'Geboortedatum kan niet in de toekomst liggen.',result:'YOUR FAMILY SCENT',top:'Topnoten',heart:'Hart',base:'Basis',story:'Het verhaal van jullie geur',basis:'Waarom deze noten',composition:'Samenstelling van de familiecode',metrics:['Maanverbinding','Venusharmonie','Zonidentiteit','Elementenbalans','Synastriesignatuur'],facts:'Basis van de berekening',house:'huis',orderTitle:'Maak een persoonlijke kaars',orderText:'Ella ontvangt de geurnaam, samenstelling en code. Gedetailleerde geboortegegevens worden niet meegestuurd.',aboutLabel:'Vertel iets over jezelf en je bestelling',aboutPlaceholder:'Voor wie de kaars is, de gelegenheid, geliefde of ongewenste geurnoten, gevoeligheid voor geuren, land van bezorging…',aboutHint:'Optioneel. Deze tekst wordt alleen toegevoegd aan je bericht aan Ella.',messageTitle:'Bestelling Family Scent Code',scentLabel:'Geur',extraLabel:'Over de klant en wensen',whatsapp:'Bestel via WhatsApp',email:'Bestel via e-mail',safety:'De kaarsformule hoort kaarsgeschikte fragrance oils binnen de actuele IFRA-limieten te gebruiken. De geur creëert sfeer en is geen behandeling of gezondheidsproduct.',unknownFact:'tijd onbekend — Ascendant en huizen zijn weggelaten',asc:'Ascendant',savedLocal:'De berekening is op dit apparaat opgeslagen.',noAstro:'De horoscoop kon niet worden berekend. Controleer de geboortegegevens en plaats.',members:'Deelnemers'}
  };
  const NOTE={
    bergamot:{name:'Bergamot',layer:'top',element:'fire'},bloodOrange:{name:'Blood Orange',layer:'top',element:'fire'},pinkPepper:{name:'Pink Pepper',layer:'top',element:'fire'},figLeaf:{name:'Fig Leaf',layer:'top',element:'earth'},greenMandarin:{name:'Green Mandarin',layer:'top',element:'earth'},sage:{name:'Clary Sage',layer:'top',element:'earth'},whiteTea:{name:'White Tea',layer:'top',element:'air'},petitgrain:{name:'Petitgrain',layer:'top',element:'air'},lavender:{name:'Lavender',layer:'top',element:'air'},pear:{name:'Pear',layer:'top',element:'water'},lotus:{name:'Lotus Mist',layer:'top',element:'water'},marine:{name:'Mineral Water',layer:'top',element:'water'},neroli:{name:'Neroli',layer:'heart',element:'fire'},saffron:{name:'Saffron',layer:'heart',element:'fire'},orangeBlossom:{name:'Orange Blossom',layer:'heart',element:'fire'},iris:{name:'Iris',layer:'heart',element:'earth'},violetLeaf:{name:'Violet Leaf',layer:'heart',element:'earth'},oatMilk:{name:'Oat Milk',layer:'heart',element:'earth'},jasmine:{name:'Jasmine',layer:'heart',element:'air'},linden:{name:'Linden Blossom',layer:'heart',element:'air'},freesia:{name:'Freesia',layer:'heart',element:'air'},fig:{name:'Fig',layer:'heart',element:'water'},rose:{name:'Soft Rose',layer:'heart',element:'water'},waterLily:{name:'Water Lily',layer:'heart',element:'water'},amber:{name:'Golden Amber',layer:'base',element:'fire'},benzoin:{name:'Benzoin',layer:'base',element:'fire'},tonka:{name:'Tonka Bean',layer:'base',element:'fire'},cedar:{name:'Cedarwood',layer:'base',element:'earth'},sandal:{name:'Sandalwood',layer:'base',element:'earth'},vetiver:{name:'Vetiver',layer:'base',element:'earth'},musk:{name:'Soft Musk',layer:'base',element:'air'},cashmere:{name:'Cashmere Wood',layer:'base',element:'air'},paleWoods:{name:'Pale Woods',layer:'base',element:'air'},incense:{name:'White Incense',layer:'base',element:'water'},vanilla:{name:'Dry Vanilla',layer:'base',element:'water'},patchouli:{name:'Patchouli',layer:'base',element:'water'}
  };
  const BY_ELEMENT={fire:{top:['bergamot','bloodOrange','pinkPepper'],heart:['neroli','saffron','orangeBlossom'],base:['amber','benzoin','tonka']},earth:{top:['figLeaf','greenMandarin','sage'],heart:['iris','violetLeaf','oatMilk'],base:['cedar','sandal','vetiver']},air:{top:['whiteTea','petitgrain','lavender'],heart:['jasmine','linden','freesia'],base:['musk','cashmere','paleWoods']},water:{top:['pear','lotus','marine'],heart:['fig','rose','waterLily'],base:['incense','vanilla','patchouli']}};
  const REASON={
    ru:{fire:'вносит тепло, живость и семейное движение',earth:'даёт устойчивость, телесный уют и надёжную основу',air:'отражает лёгкость общения, ясность и пространство',water:'передаёт эмоциональную глубину, заботу и мягкую близость',balance:'выбрана как balancing note — она соединяет различия, не называя их плохими'},
    ua:{fire:'додає тепло, жвавість і сімейний рух',earth:'дає стійкість, тілесний затишок і надійну основу',air:'відображає легкість спілкування, ясність і простір',water:'передає емоційну глибину, турботу та м’яку близькість',balance:'обрана як balancing note — вона поєднує відмінності, не називаючи їх поганими'},
    en:{fire:'brings warmth, vitality and forward movement',earth:'gives stability, physical comfort and a dependable foundation',air:'reflects clear communication, lightness and space',water:'expresses emotional depth, care and gentle closeness',balance:'acts as a balancing note, joining contrasts without labelling them as negative'},
    nl:{fire:'brengt warmte, levendigheid en beweging',earth:'geeft stabiliteit, lichamelijk comfort en een betrouwbare basis',air:'weerspiegelt heldere communicatie, lichtheid en ruimte',water:'verbeeldt emotionele diepte, zorg en zachte nabijheid',balance:'werkt als balancing note en verbindt contrasten zonder ze negatief te noemen'}
  };
  const state={mode:'family',people:[],places:{},result:null,searchTimers:{},controllers:{}};
  const rolesFor={my:['self'],child:['child'],pair:['mother','child'],family:['mother','partner','child']};
  function lang(){const stored=localStorage.getItem('language'),html=(document.documentElement.lang||'').toLowerCase(),fromHtml=html==='uk'?'ua':html.slice(0,2);if(COPY[stored])return stored;if(typeof currentLanguage!=='undefined'&&COPY[currentLanguage])return currentLanguage;if(COPY[fromHtml])return fromHtml;return'nl';}
  function c(){return COPY[lang()];}
  const SCENT_NAMES={
    ru:{'Golden Roots':'Золотые корни','Luminous Air':'Сияющий воздух','Amber Tide':'Янтарный прилив','Silver Garden':'Серебряный сад','Velvet Roots':'Бархатные корни','Quiet Horizon':'Тихий горизонт','Solar Ember':'Солнечный жар','Deep Garden':'Глубокий сад','Clear Orbit':'Ясная орбита','Moonlit Tide':'Лунный прилив'},
    ua:{'Golden Roots':'Золоті корені','Luminous Air':'Сяюче повітря','Amber Tide':'Бурштиновий приплив','Silver Garden':'Срібний сад','Velvet Roots':'Оксамитові корені','Quiet Horizon':'Тихий обрій','Solar Ember':'Сонячне тепло','Deep Garden':'Глибокий сад','Clear Orbit':'Ясна орбіта','Moonlit Tide':'Місячний приплив'},
    en:{},
    nl:{'Golden Roots':'Gouden wortels','Luminous Air':'Stralende lucht','Amber Tide':'Ambergetij','Silver Garden':'Zilveren tuin','Velvet Roots':'Fluwelen wortels','Quiet Horizon':'Stille horizon','Solar Ember':'Zonnegloed','Deep Garden':'Diepe tuin','Clear Orbit':'Heldere baan','Moonlit Tide':'Maanlichtgetij'}
  };
  const NOTE_NAMES={
    ru:{bergamot:'Бергамот',bloodOrange:'Красный апельсин',pinkPepper:'Розовый перец',figLeaf:'Лист инжира',greenMandarin:'Зелёный мандарин',sage:'Мускатный шалфей',whiteTea:'Белый чай',petitgrain:'Петитгрейн',lavender:'Лаванда',pear:'Груша',lotus:'Лотос',marine:'Минеральная вода',neroli:'Нероли',saffron:'Шафран',orangeBlossom:'Цветок апельсина',iris:'Ирис',violetLeaf:'Лист фиалки',oatMilk:'Овсяное молоко',jasmine:'Жасмин',linden:'Цвет липы',freesia:'Фрезия',fig:'Инжир',rose:'Нежная роза',waterLily:'Водяная лилия',amber:'Золотая амбра',benzoin:'Бензоин',tonka:'Бобы тонка',cedar:'Кедр',sandal:'Сандал',vetiver:'Ветивер',musk:'Мягкий мускус',cashmere:'Кашемировое дерево',paleWoods:'Светлая древесина',incense:'Белый ладан',vanilla:'Сухая ваниль',patchouli:'Пачули'},
    ua:{bergamot:'Бергамот',bloodOrange:'Червоний апельсин',pinkPepper:'Рожевий перець',figLeaf:'Лист інжиру',greenMandarin:'Зелений мандарин',sage:'Мускатна шавлія',whiteTea:'Білий чай',petitgrain:'Петитгрейн',lavender:'Лаванда',pear:'Груша',lotus:'Лотос',marine:'Мінеральна вода',neroli:'Неролі',saffron:'Шафран',orangeBlossom:'Цвіт апельсина',iris:'Ірис',violetLeaf:'Лист фіалки',oatMilk:'Вівсяне молоко',jasmine:'Жасмин',linden:'Цвіт липи',freesia:'Фрезія',fig:'Інжир',rose:'Ніжна троянда',waterLily:'Водяна лілія',amber:'Золотий бурштин',benzoin:'Бензоїн',tonka:'Боби тонка',cedar:'Кедр',sandal:'Сандал',vetiver:'Ветивер',musk:'М’який мускус',cashmere:'Кашемірове дерево',paleWoods:'Світла деревина',incense:'Білий ладан',vanilla:'Суха ваніль',patchouli:'Пачулі'},
    en:{},
    nl:{bergamot:'Bergamot',bloodOrange:'Bloedsinaasappel',pinkPepper:'Roze peper',figLeaf:'Vijgenblad',greenMandarin:'Groene mandarijn',sage:'Scharlei',whiteTea:'Witte thee',petitgrain:'Petitgrain',lavender:'Lavendel',pear:'Peer',lotus:'Lotusnevel',marine:'Mineraalwater',neroli:'Neroli',saffron:'Saffraan',orangeBlossom:'Oranjebloesem',iris:'Iris',violetLeaf:'Viooltjesblad',oatMilk:'Havermelk',jasmine:'Jasmijn',linden:'Lindebloesem',freesia:'Freesia',fig:'Vijg',rose:'Zachte roos',waterLily:'Waterlelie',amber:'Gouden amber',benzoin:'Benzoë',tonka:'Tonkaboon',cedar:'Cederhout',sandal:'Sandelhout',vetiver:'Vetiver',musk:'Zachte musk',cashmere:'Kasjmierhout',paleWoods:'Licht hout',incense:'Witte wierook',vanilla:'Droge vanille',patchouli:'Patchoeli'}
  };
  const ORDER_COPY={
    ru:{result:'АРОМАТ ВАШЕЙ СЕМЬИ',title:'Заказ Family Scent Code',candle:'Свеча',forWhom:'Аромат составлен для',name:'Ваше имя',namePlaceholder:'Как к вам обращаться',contact:'Телефон или email',contactPlaceholder:'+31… или name@email.com',customer:'Заказчик',contactLine:'Контакт',hint:'Эти данные будут добавлены в сообщение Элле.'},
    ua:{result:'АРОМАТ ВАШОЇ СІМ’Ї',title:'Замовлення Family Scent Code',candle:'Свічка',forWhom:'Аромат створено для',name:'Ваше ім’я',namePlaceholder:'Як до вас звертатися',contact:'Телефон або email',contactPlaceholder:'+31… або name@email.com',customer:'Замовник',contactLine:'Контакт',hint:'Ці дані буде додано до повідомлення Еллі.'},
    en:{result:'YOUR FAMILY SCENT',title:'Family Scent Code order',candle:'Candle',forWhom:'Scent created for',name:'Your name',namePlaceholder:'How should we address you?',contact:'Phone or email',contactPlaceholder:'+31… or name@email.com',customer:'Customer',contactLine:'Contact',hint:'These details will be added to your message to Ella.'},
    nl:{result:'DE GEUR VAN UW FAMILIE',title:'Bestelling Family Scent Code',candle:'Kaars',forWhom:'Geur samengesteld voor',name:'Uw naam',namePlaceholder:'Hoe mogen we u aanspreken?',contact:'Telefoon of e-mail',contactPlaceholder:'+31… of name@email.com',customer:'Klant',contactLine:'Contact',hint:'Deze gegevens worden toegevoegd aan uw bericht aan Ella.'}
  };
  function noteName(key){return NOTE_NAMES[lang()]?.[key]||NOTE[key].name}
  function scentName(name){return SCENT_NAMES[lang()]?.[name]||name}
  function oc(){const copy=ORDER_COPY[lang()],code=document.querySelector('.scent-code');if(code)code.textContent=copy.result;return copy}
  function esc(v){return String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));}
  function today(){const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);}
  function freshPerson(role,index){return {key:`${role}-${index}`,role,name:'',birthDate:'',birthTime:'',unknown:false,place:null,placeQuery:'',savedChildId:''};}
  function ensurePeople(){const roles=rolesFor[state.mode];const old=state.people;state.people=roles.map((role,i)=>old.find(p=>p.role===role)||freshPerson(role,i));}
  function icon(role){return role==='child'?'👶':role==='mother'?'♡':role==='partner'?'♢':'✦';}
  function savedChildren(){try{return JSON.parse(localStorage.getItem('children')||'[]')}catch(_){return[]}}
  function modeMarkup(){return Object.entries(c().modes).map(([key,val])=>`<button class="scent-mode ${state.mode===key?'active':''}" type="button" data-scent-mode="${key}"><span class="scent-mode-icon">${key==='my'?'✦':key==='child'?'☾':key==='pair'?'♡': '⌂'}</span><strong>${val[0]}</strong><small>${val[1]}</small></button>`).join('')}
  function personMarkup(p,index){const saved=p.role==='child'?savedChildren():[];const savedSelect=saved.length?`<div class="scent-field scent-place"><label>${c().saved}</label><select data-saved-child="${index}"><option value="">${c().select}</option>${saved.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.birthDate||'')}</option>`).join('')}</select></div>`:'';return `<div class="scent-person" data-person="${index}"><div class="scent-person-head"><div class="scent-person-title"><span class="scent-role-badge">${icon(p.role)}</span>${c().roles[p.role]}</div></div>${savedSelect}<div class="scent-fields"><div class="scent-field"><label>${c().name}</label><input data-field="name" value="${esc(p.name)}" autocomplete="name"></div><div class="scent-field"><label>${c().date}</label><input data-field="birthDate" type="date" max="${today()}" value="${esc(p.birthDate)}"></div><div class="scent-field"><label>${c().time}</label><div class="scent-time-row"><input data-field="birthTime" type="time" value="${esc(p.birthTime)}" ${p.unknown?'disabled':''}><label class="scent-unknown"><input data-field="unknown" type="checkbox" ${p.unknown?'checked':''}> ${c().unknown}</label></div></div><div class="scent-field scent-place"><label>${c().place}</label><input data-field="placeQuery" type="search" autocomplete="off" value="${esc(p.placeQuery)}"><div class="scent-city-status" data-city-status>${p.place?`✓ ${esc(p.place.label)}`:c().cityHint}</div><div class="scent-city-results" data-city-results></div></div></div></div>`}
  function render(){ensurePeople();const root=document.getElementById('familyScentApp');if(!root)return;root.innerHTML=`<div class="family-scent-shell"><div class="scent-hero"><div class="scent-kicker">CHILD ASTROLOGY · Ella Kristioglo</div><h2>FAMILY SCENT CODE</h2><p>${c().subtitle}</p><div class="scent-mode-grid" aria-label="${c().choose}">${modeMarkup()}</div></div><div class="scent-form-card"><div class="scent-form-head"><div><h3>${c().details}</h3><p>${c().help}</p></div></div><div class="scent-members">${state.people.map(personMarkup).join('')}</div><div class="scent-actions"><button class="scent-calculate" type="button">${c().calculate}</button><div class="scent-form-error" role="alert"></div><span class="scent-save-note">${c().savedLocal}</span></div></div><div id="familyScentResult">${state.result?resultMarkup(state.result):''}</div></div>`;bind();}
  function bind(){document.querySelectorAll('[data-scent-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.scentMode;state.people=[];state.result=null;render()}));document.querySelectorAll('[data-person]').forEach(card=>{const i=Number(card.dataset.person),p=state.people[i];card.querySelectorAll('[data-field]').forEach(input=>input.addEventListener('input',()=>{const f=input.dataset.field;if(f==='unknown'){p.unknown=input.checked;p.birthTime=p.unknown?'':p.birthTime;card.querySelector('[data-field="birthTime"]').disabled=p.unknown}else{p.savedChildId='';p[f]=input.value;if(f==='placeQuery'&&p.place&&input.value!==p.place.label)p.place=null;if(f==='placeQuery')scheduleCity(i,input.value,card)}}));card.querySelector('[data-saved-child]')?.addEventListener('change',e=>fillSaved(i,e.target.value));});document.querySelector('.scent-calculate')?.addEventListener('click',calculate);bindOrderActions()}

  function orderMessage(r,customerName,contact){const people=r.charts.map(x=>x.person.name).join(' · '),copy=c(),order=oc(),lines=[order.title,`${order.candle}: “${scentName(r.name)}”`,`${order.forWhom}: ${people}`,'',`${copy.top}: ${r.top.map(noteName).join(', ')}`,`${copy.heart}: ${r.heart.map(noteName).join(', ')}`,`${copy.base}: ${r.base.map(noteName).join(', ')}`,'',`${order.customer}: ${customerName.trim()}`,`${order.contactLine}: ${contact.trim()}`];return lines.join('\n')}
  function orderConsentText(){return lang()==='ru'?'Я понимаю, что имя, контакт и сообщение будут переданы Элле через выбранный WhatsApp или email.':lang()==='ua'?'Я розумію, що ім’я, контакт і повідомлення буде передано Еллі через вибраний WhatsApp або email.':lang()==='nl'?'Ik begrijp dat mijn naam, contactgegevens en bericht via de gekozen WhatsApp of e-mail aan Ella worden gestuurd.':'I understand that my name, contact details and message will be sent to Ella through the selected WhatsApp or email.'}
  function localiseResultUi(){if(!state.result)return;const order=oc(),result=state.result;const name=document.querySelector('.scent-name');if(name)name.textContent=`“${scentName(result.name)}”`;document.querySelectorAll('.scent-layer strong').forEach((node,index)=>{const keys=[result.top,result.heart,result.base][index];if(keys)node.textContent=keys.map(noteName).join(' · ')});document.querySelectorAll('.scent-note-reason strong').forEach((node,index)=>{const keys=[result.top[0],result.heart[0],result.base[0],result.balancing].filter(Boolean);if(keys[index])node.textContent=noteName(keys[index])});const profile=document.querySelector('.scent-order-profile');if(profile)profile.innerHTML=`<label>${order.title}</label><div class="scent-order-fields"><label for="scentOrderName">${order.name}<input id="scentOrderName" autocomplete="name" placeholder="${esc(order.namePlaceholder)}"></label><label for="scentOrderContact">${order.contact}<input id="scentOrderContact" autocomplete="email" placeholder="${esc(order.contactPlaceholder)}"></label></div><small>${order.hint}</small><label class="scent-order-consent"><input id="scentOrderConsent" type="checkbox"> <span>${esc(orderConsentText())}</span></label><div class="scent-order-error" role="alert"></div>`}
  function bindOrderActions(){localiseResultUi();document.querySelectorAll('[data-scent-order]').forEach(button=>button.addEventListener('click',()=>{if(!state.result)return;const customerName=document.getElementById('scentOrderName')?.value||'',contact=document.getElementById('scentOrderContact')?.value||'',confirmed=document.getElementById('scentOrderConsent')?.checked;if(!customerName.trim()||!contact.trim()||!confirmed){document.querySelector('.scent-order-error').textContent=lang()==='ru'?'Введите имя и контакт, затем подтвердите передачу сообщения.':lang()==='ua'?'Вкажіть ім’я й контакт, потім підтвердьте передавання повідомлення.':lang()==='nl'?'Vul naam en contact in en bevestig daarna het verzenden van het bericht.':'Enter your name and contact details, then confirm sending the message.';return}document.querySelector('.scent-order-error').textContent='';const message=orderMessage(state.result,customerName,contact);document.dispatchEvent(new CustomEvent('app:scent-order',{detail:{mode:state.mode}}));if(button.dataset.scentOrder==='whatsapp'){window.open(`https://wa.me/31612554778?text=${encodeURIComponent(message)}`,'_blank','noopener')}else{window.location.href=`mailto:ellakristioglo@gmail.com?subject=${encodeURIComponent(`${oc().title} — ${scentName(state.result.name)}`)}&body=${encodeURIComponent(message)}`}}))}
  function fillSaved(i,id){const child=savedChildren().find(x=>String(x.id)===String(id));if(!child)return;state.people[i]={...state.people[i],savedChildId:String(child.id),name:child.name||'',birthDate:child.birthDate||'',birthTime:child.birthTime||'',unknown:Boolean(child.birthTimeUnknown),place:{label:child.birthPlace,city:child.birthCity||'',region:child.birthRegion||'',country:child.birthCountry||'',countryCode:child.birthCountryCode||'',timezone:child.timezone||''},placeQuery:child.birthPlace||''};render();}
  function scheduleCity(i,q,card){clearTimeout(state.searchTimers[i]);const status=card.querySelector('[data-city-status]'),results=card.querySelector('[data-city-results]');results.innerHTML='';if(q.trim().length<3){status.textContent=c().cityHint;return}status.innerHTML=`<span class="scent-spinner"></span>${c().cityLoading}`;state.searchTimers[i]=setTimeout(()=>searchCity(i,q.trim(),card),400)}
  async function searchCity(i,q,card){const status=card.querySelector('[data-city-status]'),results=card.querySelector('[data-city-results]');try{const cities=await window.LocalCitySearch.search(q,lang(),8);if(!cities.length){status.textContent=c().cityNone;status.classList.add('error');return}status.textContent='';status.classList.remove('error');results.innerHTML=cities.map((x,n)=>`<button type="button" class="scent-city-option" data-city="${n}"><strong>${esc(x.city)}</strong><small>${esc([x.region,x.country].filter(Boolean).join(' — '))}</small></button>`).join('');results.querySelectorAll('[data-city]').forEach(b=>b.addEventListener('click',()=>{const city=cities[Number(b.dataset.city)];state.people[i].savedChildId='';state.people[i].place=city;state.people[i].placeQuery=city.label;card.querySelector('[data-field="placeQuery"]').value=city.label;status.textContent=`✓ ${city.label}`;results.innerHTML=''}))}catch(_){status.textContent=c().cityError;status.classList.add('error')}}
  function validate(){for(const p of state.people){const saved=p.savedChildId&&savedChildren().find(x=>String(x.id)===String(p.savedChildId)&&x.natalChart);if(!saved&&(!p.name||!p.birthDate||(!p.unknown&&!p.birthTime)||!p.place||!p.place.timezone))return c().required;if(p.birthDate>today())return c().future}return''}
  function angle(a,b){const d=Math.abs(a-b);return Math.min(d,360-d)}
  function aspectScore(a,b){const d=angle(a,b),targets=[0,60,90,120,180];const delta=Math.min(...targets.map(x=>Math.abs(x-d)));return Math.max(0,1-delta/12)}
  function scoreNotes(charts){const scores={};const add=(key,value)=>scores[key]=(scores[key]||0)+value;charts.forEach(({chart})=>{const factors=[['Moon',30],['Venus',20],['Sun',15],['Mercury',10]];factors.forEach(([body,w])=>{const pos=chart.positions[body],el=ELEMENT[pos.sign],pool=BY_ELEMENT[el][body==='Moon'||body==='Venus'?'heart':body==='Mercury'?'top':'base'];pool.forEach((key,n)=>add(key,w*(1-(n*.16))));});if(chart.knownTime){const el=ELEMENT[Math.floor(chart.ascendant/30)%12];BY_ELEMENT[el].top.forEach((key,n)=>add(key,15*(1-n*.18)));const houseAccents={3:['whiteTea','petitgrain'],4:['fig','cedar','sandal'],5:['bergamot','neroli'],7:['rose','musk'],12:['lotus','incense']};['Moon','Venus','Sun','Mercury'].forEach(body=>(houseAccents[chart.positions[body].house]||[]).forEach((key,n)=>add(key,6*(1-n*.2))))}else{const el=ELEMENT[chart.positions.Moon.sign];BY_ELEMENT[el].heart.forEach((key,n)=>add(key,7*(1-n*.18)))}Object.entries(BY_ELEMENT[chart.dominantElement]).forEach(([layer,pool])=>pool.forEach((key,n)=>add(key,10*(1-n*.2))))});if(charts.length>1){for(let i=0;i<charts.length;i++)for(let j=i+1;j<charts.length;j++){const a=charts[i].chart.positions,b=charts[j].chart.positions;const links=[['Moon','Moon'],['Moon','Venus'],['Venus','Venus'],['Sun','Jupiter']];links.forEach(([x,y])=>{const strength=aspectScore(a[x].longitude,b[y].longitude);if(strength>.25){const el=ELEMENT[a[x].sign];BY_ELEMENT[el][x==='Sun'?'top':'heart'].forEach((k,n)=>add(k,12*strength*(1-n*.2)))}});const tension=Math.max(aspectScore(a.Moon.longitude,b.Saturn.longitude),aspectScore(a.Venus.longitude,b.Pluto.longitude));if(tension>.35){['cedar','sandal','whiteTea'].forEach((k,n)=>add(k,10*tension*(1-n*.2)))}}}return scores}
  function pick(scores,layer,count=3){return Object.keys(NOTE).filter(k=>NOTE[k].layer===layer).sort((a,b)=>(scores[b]||0)-(scores[a]||0)).slice(0,count)}
  function makeName(charts,scores){const counts={fire:0,earth:0,air:0,water:0};charts.forEach(x=>counts[x.chart.dominantElement]++);const order=Object.keys(counts).filter(x=>counts[x]>0).sort((a,b)=>counts[b]-counts[a]);const names={fire:{earth:'Golden Roots',air:'Luminous Air',water:'Amber Tide'},earth:{fire:'Golden Roots',air:'Silver Garden',water:'Velvet Roots'},air:{fire:'Luminous Air',earth:'Silver Garden',water:'Quiet Horizon'},water:{fire:'Amber Tide',earth:'Velvet Roots',air:'Quiet Horizon'}};return (order[1]&&names[order[0]][order[1]])||({fire:'Solar Ember',earth:'Deep Garden',air:'Clear Orbit',water:'Moonlit Tide'}[order[0]])}
  function composition(charts){let moon=30,venus=22,sun=18,elements=15,syn=15;if(charts.length>1){const links=[];for(let i=0;i<charts.length;i++)for(let j=i+1;j<charts.length;j++){links.push(aspectScore(charts[i].chart.positions.Moon.longitude,charts[j].chart.positions.Moon.longitude));links.push(aspectScore(charts[i].chart.positions.Venus.longitude,charts[j].chart.positions.Venus.longitude))}const avg=links.reduce((a,b)=>a+b,0)/(links.length||1);moon+=Math.round(avg*4);syn+=Math.round(avg*5);elements-=Math.round(avg*3);venus-=Math.round(avg*2);sun-=Math.round(avg*4)}const vals=[moon,venus,sun,elements,syn],sum=vals.reduce((a,b)=>a+b,0);return vals.map(x=>Math.round(x/sum*100)).map((x,i,a)=>i===a.length-1?100-a.slice(0,-1).reduce((p,q)=>p+q,0):x)}
  function story(result){const dom=result.dominant,second=result.secondary,balancing=result.balancing?noteName(result.balancing):'';const text={ru:`Аромат открывается ${REASON.ru[dom]}. Сердце композиции собрано вокруг лунных и венерианских связей — того, как в семье ощущаются забота, близость и удовольствие от совместной жизни. Древесная база удерживает композицию и символизирует границы, надёжность и то, что помогает семье возвращаться друг к другу. ${result.balancing?`Контрастные связи в синастрии не названы проблемой: ${balancing} добавлена как балансирующая нота.`:''}`,ua:`Аромат відкривається так, що ${REASON.ua[dom]}. Серце композиції зібране навколо місячних і венеріанських зв’язків — способу відчувати турботу, близькість і радість спільного життя. Деревна база символізує межі, надійність і повернення одне до одного. ${result.balancing?`${balancing} додана як балансувальна нота для поєднання контрастів.`:''}`,en:`The scent opens with a note that ${REASON.en[dom]}. Its heart is built around Moon and Venus connections: how care, closeness and shared pleasure are experienced in the family. A woody base holds the composition, representing boundaries, reliability and the way this family finds its way back to one another. ${result.balancing?`${balancing} acts as a balancing note for contrasting synastry patterns.`:''}`,nl:`De geur opent met een noot die ${REASON.nl[dom]}. Het hart is opgebouwd rond Maan- en Venusverbindingen: hoe zorg, nabijheid en gezamenlijk plezier worden beleefd. Een houtachtige basis draagt de compositie en staat voor grenzen, betrouwbaarheid en het vermogen elkaar terug te vinden. ${result.balancing?`${balancing} werkt als balancerende noot bij contrasterende synastriepatronen.`:''}`};return text[lang()]}
  function calculate(){const error=validate(),err=document.querySelector('.scent-form-error');if(error){err.textContent=error;return}err.textContent='';const button=document.querySelector('.scent-calculate');button.disabled=true;button.innerHTML=`<span class="scent-spinner"></span>${c().working}`;setTimeout(()=>{try{const charts=state.people.map(p=>{const saved=p.savedChildId?savedChildren().find(x=>String(x.id)===String(p.savedChildId)):null;if(saved)return {person:p,chart:window.calculateChildNatalChart(saved,false)};const input={name:p.name,birthDate:p.birthDate,birthTime:p.birthTime,birthTimeUnknown:p.unknown,birthPlace:p.place.label,birthCity:p.place.city,birthRegion:p.place.region,birthCountry:p.place.country,birthCountryCode:p.place.countryCode,latitude:p.place.latitude,longitude:p.place.longitude,timezone:p.place.timezone};return {person:p,chart:window.calculateChildNatalChart(input,true)}});const scores=scoreNotes(charts),top=pick(scores,'top'),heart=pick(scores,'heart'),base=pick(scores,'base');const elementTotals={fire:0,earth:0,air:0,water:0};charts.forEach(x=>{elementTotals[x.chart.dominantElement]++});const elems=Object.keys(elementTotals).sort((a,b)=>elementTotals[b]-elementTotals[a]);const hasTension=charts.length>1&&charts.some((x,i)=>charts.slice(i+1).some(y=>aspectScore(x.chart.positions.Moon.longitude,y.chart.positions.Saturn.longitude)>.5));state.result={name:makeName(charts,scores),top,heart,base,charts,composition:composition(charts),dominant:elems[0],secondary:elems[1],balancing:hasTension?'whiteTea':null,createdAt:new Date().toISOString()};localStorage.setItem(STORE,JSON.stringify({mode:state.mode,result:serialiseResult(state.result)}));document.dispatchEvent(new CustomEvent('app:scent-generated',{detail:{mode:state.mode}}));document.getElementById('familyScentResult').innerHTML=resultMarkup(state.result);bindOrderActions();document.getElementById('familyScentResult').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){err.textContent=c().noAstro;console.error(e)}finally{button.disabled=false;button.textContent=c().calculate}},30)}
  function serialiseResult(r){return {name:r.name,top:r.top,heart:r.heart,base:r.base,composition:r.composition,dominant:r.dominant,secondary:r.secondary,balancing:r.balancing,createdAt:r.createdAt,people:r.charts.map(x=>({name:x.person.name,role:x.person.role,knownTime:x.chart.knownTime,positions:Object.fromEntries(['Sun','Moon','Mercury','Venus'].map(b=>[b,{sign:x.chart.positions[b].sign,house:x.chart.positions[b].house}])),ascendant:x.chart.ascendant}))}}
  function restoreResult(raw){if(!raw)return null;return {...raw,charts:(raw.people||[]).map(x=>({person:{name:x.name,role:x.role},chart:{knownTime:x.knownTime,positions:x.positions,ascendant:x.ascendant}}))}}
  function noteReason(key){const n=NOTE[key];return `${REASON[lang()][n.element]}.`}
  function sign(i){return SIGNS[lang()][i]}
  function resultMarkup(r){const people=r.charts.map(x=>x.person.name).join(' · '),layers=[['top',r.top],['heart',r.heart],['base',r.base]],facts=r.charts.map(x=>{const p=x.chart.positions,house=body=>x.chart.knownTime&&p[body].house?` · ${p[body].house} ${c().house}`:'';return `<div class="scent-fact"><strong>${esc(x.person.name)}</strong> — ☾ ${sign(p.Moon.sign)}${house('Moon')} · ♀ ${sign(p.Venus.sign)}${house('Venus')} · ☉ ${sign(p.Sun.sign)}${house('Sun')} · ☿ ${sign(p.Mercury.sign)}${house('Mercury')}${x.chart.knownTime&&x.chart.ascendant!=null?` · ${c().asc} ${sign(Math.floor(x.chart.ascendant/30)%12)}`:` · ${c().unknownFact}`}</div>`}).join('');return `<article class="scent-result"><div class="scent-result-top"><div><div class="scent-code">${c().result}</div><div class="scent-name">“${esc(r.name)}”</div><div class="scent-members-line">${c().members}: ${esc(people)}</div></div><div class="scent-bottle" aria-hidden="true"></div></div><div class="scent-pyramid">${layers.map(([layer,keys])=>`<div class="scent-layer"><span>${c()[layer]}</span><strong>${keys.map(k=>NOTE[k].name).join(' · ')}</strong></div>`).join('')}</div><div class="scent-story"><h4>${c().story}</h4>${story(r)}</div><div class="scent-note-reasons"><div class="scent-note-reason"><strong>${NOTE[r.top[0]].name}</strong><p>${noteReason(r.top[0])}</p></div><div class="scent-note-reason"><strong>${NOTE[r.heart[0]].name}</strong><p>${noteReason(r.heart[0])}</p></div><div class="scent-note-reason"><strong>${NOTE[r.base[0]].name}</strong><p>${noteReason(r.base[0])}</p></div>${r.balancing?`<div class="scent-note-reason"><strong>${NOTE[r.balancing].name} · Balancing note</strong><p>${REASON[lang()].balance}.</p></div>`:''}</div><div class="scent-balance"><h4>${c().composition}</h4>${c().metrics.map((label,i)=>`<div class="scent-meter"><span>${label}</span><div class="scent-meter-track"><i style="width:${r.composition[i]}%"></i></div><b>${r.composition[i]}%</b></div>`).join('')}</div><div class="scent-astro-facts"><h4>${c().facts}</h4>${facts}</div><div class="scent-order"><h4>${c().orderTitle}</h4><p>${c().orderText}</p><div class="scent-order-profile"><label for="scentOrderAbout">${c().aboutLabel}</label><textarea id="scentOrderAbout" maxlength="900" placeholder="${esc(c().aboutPlaceholder)}"></textarea><small>${c().aboutHint}</small></div><div class="scent-order-buttons"><button type="button" class="scent-order-btn whatsapp" data-scent-order="whatsapp">◉ ${c().whatsapp}</button><button type="button" class="scent-order-btn email" data-scent-order="email">✉ ${c().email}</button></div><small class="scent-safety">${c().safety}</small></div></article>`}
  window.renderFamilyScent=render;
  document.addEventListener('DOMContentLoaded',()=>{try{const saved=JSON.parse(localStorage.getItem(STORE)||'null');const created=Date.parse(saved?.result?.createdAt||'');if(saved&&Number.isFinite(created)&&Date.now()-created<=RETENTION_MS){state.mode=saved.mode||'family';state.result=restoreResult(saved.result)}else if(saved){localStorage.removeItem(STORE)}}catch(_){localStorage.removeItem(STORE)}render()});
  document.addEventListener('app:child-deleted',()=>{state.result=null;render()});
  const previousLanguage=window.changeLanguage;window.changeLanguage=function(language,event){previousLanguage(language,event);render()};
})();
