(function multilingualPostConsentGuide(){
  'use strict';
  const GUIDE_KEY='child_astrology_post_consent_guide_20260902_v1';
  const PARENT_KEY='child_astrology_parent_confirmed_v1';
  const COPY={
    ru:{next:'Далее',finish:'Начать',skip:'Пропустить',pages:[['👶','Добавьте ребёнка','Создайте профиль ребёнка с датой, временем и местом рождения. После этого откроется персональный разбор.'],['✨','Используйте методы','В разделе «Методы» собраны обучение по Меркурию, спорт по Марсу, 10 советов и метод 6 шагов.'],['💬','Задавайте вопросы','Помощник для родителей поможет сформулировать наблюдения и вопросы. Таро и Parent Scent находятся в отдельных разделах.']]},
    ua:{next:'Далі',finish:'Почати',skip:'Пропустити',pages:[['👶','Додайте дитину','Створіть профіль дитини з датою, часом і місцем народження. Після цього відкриється персональний розбір.'],['✨','Використовуйте методи','У розділі «Методи» зібрані навчання за Меркурієм, спорт за Марсом, 10 порад і метод 6 кроків.'],['💬','Ставте запитання','Помічник для батьків допоможе сформулювати спостереження та запитання. Таро і Parent Scent знаходяться в окремих розділах.']]},
    en:{next:'Next',finish:'Start',skip:'Skip',pages:[['👶','Add a child','Create a child profile with birth date, time and place. You will then get a personalised analysis.'],['✨','Use the methods','The Methods section includes Mercury learning, Mars sports, 10 tips and the 6-step method.'],['💬','Ask questions','The parent guide helps you explore observations and questions. Tarot and Parent Scent are available in their own sections.']]},
    nl:{next:'Volgende',finish:'Starten',skip:'Overslaan',pages:[['👶','Voeg een kind toe','Maak een kinderprofiel met geboortedatum, tijd en plaats. Daarna krijg je een persoonlijke analyse.'],['✨','Gebruik de methodes','Onder Methodes vind je leren via Mercurius, sport via Mars, 10 tips en de 6-stappenmethode.'],['💬','Stel vragen','De oudergids helpt je observaties en vragen te verkennen. Tarot en Parent Scent staan in aparte onderdelen.']]}
  };
  const lang=()=>COPY[localStorage.getItem('language')]?localStorage.getItem('language'):(COPY[window.currentLanguage]?window.currentLanguage:'nl');
  function consentAccepted(){try{const v=JSON.parse(localStorage.getItem(PARENT_KEY)||'null');return Boolean(v&&v.launchGate===true);}catch(_){return false;}}
  function installStyle(){if(document.getElementById('postConsentGuideStyles'))return;const s=document.createElement('style');s.id='postConsentGuideStyles';s.textContent=`
    .post-consent-guide{position:fixed;inset:0;z-index:21000;background:rgba(20,13,57,.82);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:18px}.post-consent-card{width:min(520px,100%);background:#fff;border-radius:28px;padding:26px;box-shadow:0 28px 90px rgba(0,0,0,.4);color:#283246}.post-consent-icon{font-size:48px}.post-consent-card h2{color:#5b2b87;font-size:clamp(28px,7vw,38px);line-height:1.05;margin:10px 0 12px}.post-consent-card p{font-size:17px;line-height:1.6;margin:0 0 22px}.post-consent-actions{display:flex;align-items:center;gap:10px}.post-consent-actions .count{margin-left:auto;margin-right:auto;font-size:13px;opacity:.6}.post-consent-actions button{min-height:48px;border-radius:15px;padding:0 18px;border:1px solid #ddd;background:#fff;font-weight:800}.post-consent-actions .primary{border:0;background:#f3ca35;color:#3f235f}@media(max-width:600px){.post-consent-guide{align-items:flex-end;padding:10px}.post-consent-card{border-radius:26px 26px 18px 18px;padding:22px 18px}}
  `;document.head.appendChild(s);}
  function closeGuide(){localStorage.setItem(GUIDE_KEY,'done');document.querySelector('.post-consent-guide')?.remove();document.querySelector('.app')?.removeAttribute('inert');document.querySelector('.mobile-bottom-nav')?.removeAttribute('inert');window.showSection?.('home');}
  function render(step=0){if(localStorage.getItem(GUIDE_KEY)==='done'||!consentAccepted())return;installStyle();const text=COPY[lang()]||COPY.nl;let root=document.querySelector('.post-consent-guide');if(!root){root=document.createElement('div');root.className='post-consent-guide';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');document.body.appendChild(root);}document.querySelector('.app')?.setAttribute('inert','');document.querySelector('.mobile-bottom-nav')?.setAttribute('inert','');const page=text.pages[step];root.innerHTML=`<div class="post-consent-card"><div class="post-consent-icon" aria-hidden="true">${page[0]}</div><h2>${page[1]}</h2><p>${page[2]}</p><div class="post-consent-actions"><button type="button" data-guide-skip>${text.skip}</button><span class="count">${step+1}/3</span><button type="button" class="primary" data-guide-next>${step===2?text.finish:text.next}</button></div></div>`;root.querySelector('[data-guide-skip]').onclick=closeGuide;root.querySelector('[data-guide-next]').onclick=()=>step===2?closeGuide():render(step+1);window.AppModalFocus?.activate(root,'[data-guide-next]');}
  function maybeShow(){if(localStorage.getItem(GUIDE_KEY)==='done'||!consentAccepted())return;if(document.querySelector('.launch-gate'))return;setTimeout(()=>render(0),80);}
  window.addEventListener('load',()=>{maybeShow();const observer=new MutationObserver(()=>maybeShow());observer.observe(document.body,{childList:true});},{once:true});
})();
