(function setupSupportCenter(){
  'use strict';
  const SUPPORT_EMAIL='support@childastrologyapp.com';
  const COPY={
    ru:{nav:'Поддержка',title:'Служба поддержки',intro:'Если что-то работает неправильно или у вас есть вопрос по приложению, отправьте обращение здесь.',privacy:'Данные ребёнка, дата рождения, натальная карта и история вопросов не прикрепляются к обращению автоматически.',name:'Имя',email:'Email для ответа',topic:'Тема',message:'Сообщение',send:'Отправить в поддержку',copy:'Скопировать обращение',topics:['Проблема с приложением','Профиль ребёнка','Астрология и методы','Таро','Ароматы / свечи','Конфиденциальность','Другое'],placeholder:'Опишите, что произошло и на каком экране.',success:'Обращение подготовлено. Номер обращения:',copied:'Обращение скопировано.',required:'Заполните email и сообщение.',faq:'Частые вопросы',q1:'Почему приложение не переводит часть текста?',a1:'Переключите язык ещё раз и перезапустите экран. Если текст остаётся на другом языке, отправьте обращение со скриншотом.',q2:'Передаются ли данные ребёнка в поддержку?',a2:'Нет. Профили детей и данные рождения не добавляются к обращению автоматически.',q3:'Как удалить данные?',a3:'Используйте настройки конфиденциальности в приложении. Там можно удалить историю вопросов или все локальные данные.'},
    ua:{nav:'Підтримка',title:'Служба підтримки',intro:'Якщо щось працює неправильно або у вас є запитання щодо застосунку, надішліть звернення тут.',privacy:'Дані дитини, дата народження, натальна карта та історія запитань не додаються до звернення автоматично.',name:'Ім’я',email:'Email для відповіді',topic:'Тема',message:'Повідомлення',send:'Надіслати в підтримку',copy:'Скопіювати звернення',topics:['Проблема із застосунком','Профіль дитини','Астрологія та методи','Таро','Аромати / свічки','Конфіденційність','Інше'],placeholder:'Опишіть, що сталося і на якому екрані.',success:'Звернення підготовлено. Номер звернення:',copied:'Звернення скопійовано.',required:'Заповніть email і повідомлення.',faq:'Часті запитання',q1:'Чому застосунок не перекладає частину тексту?',a1:'Перемкніть мову ще раз і перезапустіть екран. Якщо текст залишається іншою мовою, надішліть звернення зі скриншотом.',q2:'Чи передаються дані дитини в підтримку?',a2:'Ні. Профілі дітей і дані народження не додаються до звернення автоматично.',q3:'Як видалити дані?',a3:'Використовуйте налаштування конфіденційності в застосунку. Там можна видалити історію запитань або всі локальні дані.'},
    en:{nav:'Support',title:'Support',intro:'If something is not working correctly or you have a question about the app, send a support request here.',privacy:"Your child's profile, birth details, birth chart and question history are never attached to a support request automatically.",name:'Name',email:'Reply email',topic:'Topic',message:'Message',send:'Email support',copy:'Copy request',topics:['App problem','Child profile','Astrology & methods','Tarot','Scents / candles','Privacy','Other'],placeholder:'Describe what happened and which screen you were using.',success:'Your request is ready. Request ID:',copied:'Support request copied.',required:'Please enter your email and message.',faq:'Frequently asked questions',q1:'Why is some text not translated?',a1:'Switch the language once more and reopen the screen. If text remains in another language, create a request and include a screenshot.',q2:'Are child data sent to support?',a2:'No. Child profiles and birth details are not attached to a request automatically.',q3:'How can I delete my data?',a3:'Use the Privacy settings in the app. You can delete question history or all locally stored data there.'},
    nl:{nav:'Support',title:'Klantenservice',intro:'Werkt iets niet goed of heeft u een vraag over de app? Stuur hier een supportverzoek.',privacy:'Het profiel van uw kind, geboortegegevens, geboortehoroscoop en vraaggeschiedenis worden nooit automatisch aan een supportverzoek toegevoegd.',name:'Naam',email:'E-mail voor antwoord',topic:'Onderwerp',message:'Bericht',send:'E-mail naar support',copy:'Verzoek kopiëren',topics:['Probleem met de app','Kinderprofiel','Astrologie & methoden','Tarot','Geuren / kaarsen','Privacy','Anders'],placeholder:'Beschrijf wat er gebeurde en op welk scherm.',success:'Uw verzoek staat klaar. Verzoeknummer:',copied:'Supportverzoek gekopieerd.',required:'Vul uw e-mail en bericht in.',faq:'Veelgestelde vragen',q1:'Waarom is een deel van de tekst niet vertaald?',a1:'Wissel nogmaals van taal en open het scherm opnieuw. Blijft tekst in een andere taal staan, maak dan een verzoek met een screenshot.',q2:'Worden gegevens van mijn kind naar support gestuurd?',a2:'Nee. Kinderprofielen en geboortegegevens worden niet automatisch aan een verzoek toegevoegd.',q3:'Hoe verwijder ik mijn gegevens?',a3:'Gebruik de privacy-instellingen in de app. Daar kunt u de vraaggeschiedenis of alle lokaal opgeslagen gegevens verwijderen.'}
  };
  const lang=()=>{const value=localStorage.getItem('language')||window.currentLanguage||document.documentElement.lang||'nl';return COPY[value]?value:'nl';};
  const t=()=>COPY[lang()];
  function addStyle(){if(document.querySelector('link[data-support-center-style]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='support-center.css?v=20260902a';link.dataset.supportCenterStyle='1';document.head.appendChild(link);}
  function ticketId(){const d=new Date();return `CA-${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
  function getTickets(){try{return JSON.parse(localStorage.getItem('child_astrology_support_tickets_v1')||'[]');}catch(_){return[];}}
  function saveTicket(ticket){const list=getTickets();list.unshift(ticket);try{localStorage.setItem('child_astrology_support_tickets_v1',JSON.stringify(list.slice(0,25)));}catch(_){}}
  function compose(ticket){return `[${ticket.id}] Child Astrology Support\nTopic: ${ticket.topic}\nName: ${ticket.name||'-'}\nReply email: ${ticket.email}\nLanguage: ${ticket.language.toUpperCase()}\nCreated: ${ticket.createdAt}\n\n${ticket.message}`;}
  function mailto(ticket){const subject=encodeURIComponent(`[${ticket.id}] Child Astrology Support — ${ticket.topic}`);const body=encodeURIComponent(compose(ticket));return `mailto:${SUPPORT_EMAIL}?subject=${subject}&body=${body}`;}
  async function copyText(text){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return;}const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}
  function renderSection(){const section=document.getElementById('support');if(!section)return;const c=t();section.innerHTML=`<div class="support-center"><div class="support-hero"><h2>💬 ${c.title}</h2><p>${c.intro}</p><p><a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a></p><div class="support-notice">🔒 ${c.privacy}</div></div><div class="support-card"><form id="supportForm" class="support-form" novalidate><div class="support-field"><label for="supportName">${c.name}</label><input id="supportName" name="name" autocomplete="name"></div><div class="support-field"><label for="supportEmail">${c.email}</label><input id="supportEmail" name="email" type="email" autocomplete="email" required></div><div class="support-field"><label for="supportTopic">${c.topic}</label><select id="supportTopic" name="topic">${c.topics.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="support-field"><label for="supportMessage">${c.message}</label><textarea id="supportMessage" name="message" placeholder="${c.placeholder}" required></textarea></div><div class="support-actions"><button class="support-btn support-btn-primary" type="submit">${c.send}</button><button class="support-btn support-btn-secondary" type="button" id="supportCopy" disabled>${c.copy}</button></div><div class="support-status" id="supportStatus" role="status" aria-live="polite"></div></form></div><div class="support-card support-faq"><h3>❓ ${c.faq}</h3><details><summary>${c.q1}</summary><p>${c.a1}</p></details><details><summary>${c.q2}</summary><p>${c.a2}</p></details><details><summary>${c.q3}</summary><p>${c.a3}</p></details></div></div>`;
    let lastTicket=null;const form=section.querySelector('#supportForm');const status=section.querySelector('#supportStatus');const copy=section.querySelector('#supportCopy');form?.addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(form);const email=String(data.get('email')||'').trim();const message=String(data.get('message')||'').trim();if(!email||!message){status.textContent=c.required;status.classList.add('show');return;}lastTicket={id:ticketId(),name:String(data.get('name')||'').trim(),email,topic:String(data.get('topic')||''),message,language:lang(),createdAt:new Date().toISOString()};saveTicket(lastTicket);status.innerHTML=`${c.success} <span class="support-ticket">${lastTicket.id}</span>`;status.classList.add('show');copy.disabled=false;window.location.href=mailto(lastTicket);});copy?.addEventListener('click',async()=>{if(!lastTicket)return;try{await copyText(compose(lastTicket));status.textContent=c.copied;status.classList.add('show');}catch(_){}});}
  function addNavigation(){const c=t();const sidebar=document.querySelector('.sidebar .nav-menu');if(sidebar&&!sidebar.querySelector('[data-section="support"]')){const li=document.createElement('li');li.className='nav-item';li.innerHTML=`<button type="button" class="nav-link" data-section="support"><span class="nav-icon support-sidebar-icon" aria-hidden="true">💬</span><span data-support-label>${c.nav}</span></button>`;sidebar.appendChild(li);}const grid=document.querySelector('#mobileMethodsMenu .mobile-methods-grid');if(grid&&!grid.querySelector('[data-section="support"]')){const button=document.createElement('button');button.type='button';button.className='mobile-method-option';button.dataset.section='support';button.innerHTML=`<span class="support-menu-icon" aria-hidden="true">💬</span><span data-support-label>${c.nav}</span>`;grid.appendChild(button);}document.querySelectorAll('[data-support-label]').forEach(el=>el.textContent=c.nav);}
  function addSection(){if(document.getElementById('support'))return;const main=document.querySelector('.main-content');if(!main)return;const section=document.createElement('section');section.id='support';section.className='section';main.appendChild(section);renderSection();}
  function bindNavigation(){document.addEventListener('click',(event)=>{const button=event.target.closest('[data-section="support"]');if(!button)return;event.preventDefault();if(typeof window.closeMobileMethods==='function')window.closeMobileMethods();if(typeof window.showSection==='function')window.showSection('support',event);else document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id==='support'));});document.addEventListener('click',(event)=>{if(!event.target.closest('[data-language]'))return;setTimeout(()=>{addNavigation();renderSection();},60);});}
  function init(){addStyle();addSection();addNavigation();bindNavigation();}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
