const tipsTranslations={
ru:{
aries:{title:'♈ ОВЕН / ARIES',tips:['Не ругать за всплески энергии. Лучше помогать направлять её в безопасное и полезное русло.','Сделать движение и спорт частью привычного режима.','Поощрять смелость, инициативу и непосредственность.','Давать возможность проявлять себя и быть замеченным.','Чаще хвалить за старания и поддерживать после неудач.','Подойдут активные танцы, театр или творческий кружок.','Разрешать приглашать друзей домой при понятных правилах.','Помогать помнить о планах и долгосрочных целях.','Избегать манипуляций, давления и эмоционального шантажа.','Учить открывать «закрытые двери» настойчивостью, а не конфликтом.']},
taurus:{title:'♉ ТЕЛЕЦ / TAURUS',tips:['Не заставлять делиться силой, лучше учить этому постепенно и через пример.','С детства знакомить с деньгами, накоплениями и простым бюджетом.','Давать больше творческих и практических заданий.','Спокойный и терпеливый преподаватель подойдёт лучше жёсткого.','Не кричать и не наказывать унизительно.','Создавать приятные семейные ритуалы вокруг еды и уюта.','Выбирать спокойные виды спорта с понятным ритмом.','Предпочитать удобную одежду и приятные материалы.','Не заставлять выступать публично, если ребёнок стесняется.','Мотивировать понятными целями и учить копить.']},
gemini:{title:'♊ БЛИЗНЕЦЫ / GEMINI',tips:['Поощрять любознательность и любовь к чтению.','Договариваться о времени с экраном вместо постоянных запретов.','Поддерживать общение со сверстниками.','Давать новые впечатления, поездки и смену обстановки.','Не драматизировать из-за нескольких начатых дел, лучше учить завершать по одному.','Много разговаривать и делиться новостями.','Рано знакомить с иностранными языками.','Спокойно относиться к бесконечным вопросам.','Строить доверительные отношения и сохранять роль взрослого.','Поддерживать интерес к учёбе и тренировать публичные выступления.']},
cancer:{title:'♋ РАК / CANCER',tips:['Критику давать мягко и конкретно, без унижения.','Не навязывать жёсткие стереотипы о том, каким ребёнок «должен» быть.','Чаще говорить о чувствах и учить называть эмоции.','Готовить вместе и создавать тёплые семейные ритуалы.','Подойдут творческие кружки и занятия с безопасной атмосферой.','Поддерживать связь с близкими родственниками.','Показывать, что уязвимость и просьба о помощи нормальны.','Учить решать конфликты через разговор.','Развивать память через истории, фотографии и ассоциации.','Защищать от унижающих и агрессивных взрослых.']},
leo:{title:'♌ ЛЕВ / LEO',tips:['Искренняя похвала очень мотивирует.','Давать творческие задачи и возможность показать результат.','Читать яркие истории и обсуждать героев.','Устраивать домашний театр, сценки и мини-презентации.','Позволять выражать себя через одежду в разумных рамках.','Помогать строить здоровые дружеские отношения.','Поддерживать интерес к видео и творчеству с правилами цифровой безопасности.','Домашние обязанности превращать в понятную ответственность, а не наказание.','Учить обращаться с деньгами и планировать покупки.','Сохранять предсказуемый режим дня.']},
virgo:{title:'♍ ДЕВА / VIRGO',tips:['Домашнее животное может учить заботе, если семья к этому готова.','Постепенно приучать к порядку и домашним обязанностям.','Поддерживать любовь к книгам и знаниям.','Поощрять интерес к природе и наблюдениям.','Давать достаточно самостоятельности.','Развивать логику и аналитическое мышление.','Чаще замечать успехи, а не только ошибки.','Учить отдыхать без чувства вины.','Показывать, как говорить о недостатках без резкой критики.','Хвалить за усилия и не ставить планку недостижимо высоко.']},
libra:{title:'♎ ВЕСЫ / LIBRA',tips:['Создавать семейные традиции совместных прогулок и занятий.','Не устраивать громкие конфликты при ребёнке.','Подойдут парные танцы и командные активности.','Разрешить участвовать в оформлении своей комнаты.','Вместе пробовать рисование, дизайн, музыку и искусство.','Помогать выбирать здоровое окружение, а не «идеальный статус».','Иногда разрешать учиться вместе с другом.','Если интересуется модой, поддержать через безопасные творческие проекты.','Учить распознавать и регулировать эмоции.','Музыка и индивидуальные творческие занятия могут хорошо подойти.']},
scorpio:{title:'♏ СКОРПИОН / SCORPIO',tips:['Подойдут спорт, единоборства и другие дисциплины с хорошим тренером.','Предлагать загадки, расследования и головоломки.','Не угрожать и не применять физические наказания.','Театр и актёрское мастерство помогают выражать сильные эмоции.','Поддерживать интерес к сцене или моделингу без давления на внешность.','Не требовать идеального порядка каждую минуту.','Давать понять, что ребёнок может рассчитывать на вашу поддержку.','Поддерживать здоровые амбиции и учить принимать поражения.','Авторитет строить на доверии и последовательности, а не на страхе.','Учить планировать дела и обращаться с деньгами.']},
sagittarius:{title:'♐ СТРЕЛЕЦ / SAGITTARIUS',tips:['Хвалить конкретно за реальные усилия и достижения.','Учить дисциплине через понятные правила и свободу внутри них.','Поддерживать новые интересы и кружки, не перегружая расписание.','Путешествовать и показывать разные культуры, когда это возможно.','Знакомить с людьми, которые увлечены делом и умеют ставить цели.','Подойдут конный спорт, теннис, лёгкая атлетика и другие активные занятия.','Учить отделять главное от второстепенного.','Домашние дела делать понятными и по возможности интересными.','Иногда спрашивать мнение ребёнка по семейным мелочам.','Позволять выбирать одежду и развивать собственный вкус.']},
capricorn:{title:'♑ КОЗЕРОГ / CAPRICORN',tips:['Учить планировать день и неделю без чрезмерного контроля.','Давать тихое отдельное место для учёбы.','Учить ценить время через распорядок, а не через постоянную спешку.','Уважать собственное мнение ребёнка и спокойно обсуждать разногласия.','Не сравнивать с другими детьми.','Строить отношения на доверии, честности и справедливости.','Поддерживать интерес к технологиям, проектам и предпринимательству.','Следить за регулярным питанием, отдыхом и движением.','Искать сильное окружение без идеи «элитарности».','Не читать длинные нотации, лучше говорить коротко и по существу.']},
aquarius:{title:'♒ ВОДОЛЕЙ / AQUARIUS',tips:['Поездки и новые места хорошо расширяют кругозор.','Поддерживать дружбу и социальные связи.','Искать учителей, которые связывают знания с современным миром.','Развивать критическое мышление и умение проверять факты.','Дисциплину вводить как систему, а не как подавление свободы.','Ходить в музеи науки, планетарии и на познавательные мероприятия.','Уважать личные границы и не навязывать физический контакт.','Позволять безопасно экспериментировать со стилем.','Не оставлять надолго в среде, где индивидуальность постоянно подавляют.','Гаджеты выбирать по необходимости, а не ради моды.']},
pisces:{title:'♓ РЫБЫ / PISCES',tips:['Знакомить с искусством, выставками и творчеством.','Одежду выбирать удобную и красивую, не делая бренды мерилом ценности.','Развивать любовь к природе и животным.','Следить за достаточным отдыхом и временем без стимулов.','Формировать здоровые привычки без жёсткого контроля.','Учить экологично выражать эмоции и просить поддержки.','Музыка, пение и творческие занятия часто хорошо подходят.','Читать истории и развивать фантазию.','После школы мягко интересоваться самочувствием и отношениями с другими.','Подойдут поэзия, театр и другие формы творческого самовыражения.']}
},
ua:{
aries:{title:'♈ ОВЕН / ARIES',tips:['Не сварити за сплески енергії. Краще допомагати спрямовувати її безпечно й корисно.','Зробити рух і спорт частиною звичного режиму.','Заохочувати сміливість, ініціативу й безпосередність.','Давати можливість проявляти себе й бути поміченим.','Частіше хвалити за старання та підтримувати після невдач.','Підійдуть активні танці, театр або творчий гурток.','Дозволяти запрошувати друзів додому за зрозумілих правил.','Допомагати пам’ятати про плани й довгострокові цілі.','Уникати маніпуляцій, тиску та емоційного шантажу.','Учити відкривати «закриті двері» наполегливістю, а не конфліктом.']},
taurus:{title:'♉ ТЕЛЕЦЬ / TAURUS',tips:['Не змушувати ділитися силоміць, краще навчати поступово й власним прикладом.','З дитинства знайомити з грошима, заощадженнями та простим бюджетом.','Давати більше творчих і практичних завдань.','Спокійний і терплячий викладач підійде краще за жорсткого.','Не кричати й не карати принизливо.','Створювати приємні сімейні ритуали навколо їжі та затишку.','Обирати спокійні види спорту зі зрозумілим ритмом.','Віддавати перевагу зручному одягу й приємним матеріалам.','Не змушувати виступати публічно, якщо дитина соромиться.','Мотивувати зрозумілими цілями й навчати заощаджувати.']},
gemini:{title:'♊ БЛИЗНЮКИ / GEMINI',tips:['Заохочувати допитливість і любов до читання.','Домовлятися про час з екраном замість постійних заборон.','Підтримувати спілкування з однолітками.','Давати нові враження, поїздки та зміну обстановки.','Не драматизувати через кілька розпочатих справ, а вчити завершувати по одній.','Багато розмовляти й ділитися новинами.','Рано знайомити з іноземними мовами.','Спокійно ставитися до нескінченних запитань.','Будувати довірливі стосунки, зберігаючи роль дорослого.','Підтримувати інтерес до навчання й тренувати публічні виступи.']},
cancer:{title:'♋ РАК / CANCER',tips:['Критику давати м’яко й конкретно, без приниження.','Не нав’язувати жорсткі стереотипи про те, якою дитина «повинна» бути.','Частіше говорити про почуття й учити називати емоції.','Готувати разом і створювати теплі сімейні ритуали.','Підійдуть творчі гуртки з безпечною атмосферою.','Підтримувати зв’язок із близькими родичами.','Показувати, що вразливість і прохання про допомогу нормальні.','Учити вирішувати конфлікти через розмову.','Розвивати пам’ять через історії, фото й асоціації.','Захищати від принизливих та агресивних дорослих.']},
leo:{title:'♌ ЛЕВ / LEO',tips:['Щира похвала дуже мотивує.','Давати творчі завдання й можливість показати результат.','Читати яскраві історії та обговорювати героїв.','Влаштовувати домашній театр, сценки й мініпрезентації.','Дозволяти самовираження через одяг у розумних межах.','Допомагати будувати здорові дружні стосунки.','Підтримувати інтерес до відео й творчості з правилами цифрової безпеки.','Домашні обов’язки робити зрозумілою відповідальністю, а не покаранням.','Учити поводитися з грошима й планувати покупки.','Зберігати передбачуваний режим дня.']},
virgo:{title:'♍ ДІВА / VIRGO',tips:['Домашня тварина може вчити турботи, якщо сім’я до цього готова.','Поступово привчати до порядку й домашніх обов’язків.','Підтримувати любов до книжок і знань.','Заохочувати інтерес до природи та спостережень.','Давати достатньо самостійності.','Розвивати логіку й аналітичне мислення.','Частіше помічати успіхи, а не лише помилки.','Учити відпочивати без почуття провини.','Показувати, як говорити про недоліки без різкої критики.','Хвалити за зусилля й не ставити недосяжно високу планку.']},
libra:{title:'♎ ТЕРЕЗИ / LIBRA',tips:['Створювати сімейні традиції спільних прогулянок і занять.','Не влаштовувати гучні конфлікти при дитині.','Підійдуть парні танці й командні активності.','Дозволити брати участь в оформленні своєї кімнати.','Разом пробувати малювання, дизайн, музику й мистецтво.','Допомагати обирати здорове оточення, а не «ідеальний статус».','Іноді дозволяти вчитися разом із другом.','Якщо цікавиться модою, підтримати через безпечні творчі проєкти.','Учити розпізнавати й регулювати емоції.','Музика та індивідуальні творчі заняття можуть добре підійти.']},
scorpio:{title:'♏ СКОРПІОН / SCORPIO',tips:['Підійдуть спорт, єдиноборства та інші дисципліни з хорошим тренером.','Пропонувати загадки, розслідування й головоломки.','Не погрожувати й не застосовувати фізичних покарань.','Театр і акторська майстерність допомагають виражати сильні емоції.','Підтримувати інтерес до сцени або моделінгу без тиску на зовнішність.','Не вимагати ідеального порядку щохвилини.','Давати зрозуміти, що дитина може розраховувати на вашу підтримку.','Підтримувати здорові амбіції й учити приймати поразки.','Авторитет будувати на довірі й послідовності, а не на страху.','Учити планувати справи й поводитися з грошима.']},
sagittarius:{title:'♐ СТРІЛЕЦЬ / SAGITTARIUS',tips:['Хвалити конкретно за реальні зусилля й досягнення.','Учити дисципліни через зрозумілі правила та свободу всередині них.','Підтримувати нові інтереси й гуртки, не перевантажуючи розклад.','Подорожувати й показувати різні культури, коли це можливо.','Знайомити з людьми, які захоплені справою й уміють ставити цілі.','Підійдуть кінний спорт, теніс, легка атлетика та інші активні заняття.','Учити відокремлювати головне від другорядного.','Домашні справи робити зрозумілими й по можливості цікавими.','Іноді питати думку дитини щодо сімейних дрібниць.','Дозволяти обирати одяг і розвивати власний смак.']},
capricorn:{title:'♑ КОЗОРІГ / CAPRICORN',tips:['Учити планувати день і тиждень без надмірного контролю.','Давати тихе окреме місце для навчання.','Учити цінувати час через розпорядок, а не через постійний поспіх.','Поважати власну думку дитини й спокійно обговорювати розбіжності.','Не порівнювати з іншими дітьми.','Будувати стосунки на довірі, чесності й справедливості.','Підтримувати інтерес до технологій, проєктів і підприємництва.','Стежити за регулярним харчуванням, відпочинком і рухом.','Шукати сильне оточення без ідеї «елітарності».','Не читати довгі нотації, краще говорити коротко й по суті.']},
aquarius:{title:'♒ ВОДОЛІЙ / AQUARIUS',tips:['Поїздки й нові місця добре розширюють кругозір.','Підтримувати дружбу та соціальні зв’язки.','Шукати вчителів, які пов’язують знання із сучасним світом.','Розвивати критичне мислення й уміння перевіряти факти.','Дисципліну вводити як систему, а не як придушення свободи.','Ходити до музеїв науки, планетаріїв і на пізнавальні заходи.','Поважати особисті межі й не нав’язувати фізичний контакт.','Дозволяти безпечно експериментувати зі стилем.','Не залишати надовго в середовищі, де індивідуальність постійно пригнічують.','Гаджети обирати за потребою, а не заради моди.']},
pisces:{title:'♓ РИБИ / PISCES',tips:['Знайомити з мистецтвом, виставками й творчістю.','Одяг обирати зручний і красивий, не роблячи бренди мірилом цінності.','Розвивати любов до природи й тварин.','Стежити за достатнім відпочинком і часом без стимулів.','Формувати здорові звички без жорсткого контролю.','Учити екологічно виражати емоції й просити підтримки.','Музика, спів і творчі заняття часто добре підходять.','Читати історії й розвивати фантазію.','Після школи м’яко цікавитися самопочуттям і стосунками з іншими.','Підійдуть поезія, театр та інші форми творчого самовираження.']}
},
en:{
aries:{title:'♈ ARIES',tips:['Do not punish bursts of energy. Help channel that energy into safe and useful activities.','Make movement and sport part of the normal routine.','Encourage courage, initiative, and spontaneity.','Give opportunities to be seen and express themselves.','Praise effort and support them after setbacks.','Active dance, theatre, or creative clubs can work well.','Let friends visit within clear family rules.','Help them remember plans and long-term goals.','Avoid manipulation, pressure, and emotional blackmail.','Teach persistence rather than conflict when something feels blocked.']},
taurus:{title:'♉ TAURUS',tips:['Do not force sharing; teach it gradually through example.','Introduce money, saving, and simple budgeting early.','Offer more creative and practical tasks.','A calm and patient teacher is often a better fit than a harsh one.','Avoid shouting or humiliating punishment.','Create pleasant family rituals around food and comfort.','Choose steady sports with a clear rhythm.','Prefer comfortable clothes and pleasant fabrics.','Do not force public performance if the child is shy.','Use clear goals as motivation and teach saving.']},
gemini:{title:'♊ GEMINI',tips:['Encourage curiosity and a love of reading.','Agree on screen-time limits instead of relying on constant bans.','Support healthy friendships with peers.','Offer new experiences, trips, and changes of scenery.','Do not panic about several unfinished projects; teach finishing one at a time.','Talk often and share news.','Introduce foreign languages early.','Stay patient with endless questions.','Build trust while keeping the adult role clear.','Support learning and practise public speaking in low-pressure ways.']},
cancer:{title:'♋ CANCER',tips:['Give criticism gently and specifically, without humiliation.','Do not impose rigid stereotypes about how the child should behave.','Talk about feelings and teach names for emotions.','Cook together and create warm family rituals.','Creative activities with a safe atmosphere may suit them well.','Maintain connection with close relatives.','Show that vulnerability and asking for help are normal.','Teach conflict resolution through conversation.','Develop memory through stories, photos, and associations.','Protect the child from humiliating or aggressive adults.']},
leo:{title:'♌ LEO',tips:['Sincere praise is highly motivating.','Offer creative tasks and chances to show the result.','Read vivid stories and discuss the characters.','Try home theatre, role-play, and mini-presentations.','Allow self-expression through clothes within sensible limits.','Help build healthy friendships.','Support video and creative interests with digital-safety rules.','Make household chores a clear responsibility, not a punishment.','Teach money skills and planning purchases.','Keep a predictable daily rhythm.']},
virgo:{title:'♍ VIRGO',tips:['A pet can teach care if the family is ready for the responsibility.','Gradually teach tidiness and age-appropriate chores.','Support a love of books and knowledge.','Encourage interest in nature and observation.','Give enough independence.','Develop logic and analytical thinking.','Notice achievements, not only mistakes.','Teach how to rest without guilt.','Model how to point out problems without harsh criticism.','Praise effort without setting an impossibly high standard.']},
libra:{title:'♎ LIBRA',tips:['Create family traditions around walks and shared activities.','Avoid loud conflict in front of the child.','Partner dance and team activities may suit them.','Let them help design their own room.','Explore drawing, design, music, and art together.','Help them choose healthy company rather than chasing status.','Sometimes let them study with a friend.','If fashion interests them, support it through safe creative projects.','Teach emotional awareness and regulation.','Music and individual creative lessons may work well.']},
scorpio:{title:'♏ SCORPIO',tips:['Sport, martial arts, and disciplined activities can be helpful with a good coach.','Offer mysteries, investigations, and puzzles.','Never threaten or use physical punishment.','Theatre and acting can help express strong emotions.','Support interest in stage work or modelling without appearance pressure.','Do not demand perfect tidiness all the time.','Make it clear that the child can rely on your support.','Encourage healthy ambition and teach how to handle losing.','Build authority through trust and consistency, not fear.','Teach planning and basic money skills.']},
sagittarius:{title:'♐ SAGITTARIUS',tips:['Praise real effort and achievements specifically.','Teach discipline through clear rules with freedom inside them.','Support new interests without overcrowding the schedule.','Travel and introduce different cultures when possible.','Let them meet people who are enthusiastic and goal-oriented.','Horse riding, tennis, athletics, and other active sports may suit them.','Teach how to separate what matters from what is secondary.','Make chores clear and, where possible, engaging.','Ask for the child’s opinion on small family decisions.','Let them choose clothes and develop their own taste.']},
capricorn:{title:'♑ CAPRICORN',tips:['Teach planning for the day and week without over-controlling.','Provide a quiet, separate place to study.','Teach respect for time through routine rather than constant rushing.','Respect the child’s opinions and discuss disagreements calmly.','Do not compare them with other children.','Build the relationship on trust, honesty, and fairness.','Support interest in technology, projects, and entrepreneurship.','Protect regular meals, rest, and movement.','Seek a strong environment without making status the goal.','Skip long lectures; be brief and specific.']},
aquarius:{title:'♒ AQUARIUS',tips:['Trips and new places can broaden their perspective.','Support friendships and social connections.','Look for teachers who connect learning with the modern world.','Develop critical thinking and fact-checking skills.','Use discipline as a supportive system, not suppression of freedom.','Visit science museums, planetariums, and educational events.','Respect personal boundaries and do not force physical affection.','Allow safe experiments with personal style.','Avoid environments where individuality is constantly suppressed.','Choose gadgets for usefulness, not simply because they are fashionable.']},
pisces:{title:'♓ PISCES',tips:['Introduce art, exhibitions, and creative activities.','Choose comfortable, attractive clothes without treating brands as a measure of worth.','Encourage love of nature and animals.','Protect enough rest and quiet time.','Build healthy habits without excessive control.','Teach healthy ways to express emotions and ask for support.','Music, singing, and creative activities may suit them well.','Read stories and encourage imagination.','After school, gently ask about feelings and relationships with others.','Poetry, theatre, and other creative forms of self-expression can be helpful.']}
},
nl:{
aries:{title:'♈ RAM / ARIES',tips:['Straf uitbarstingen van energie niet. Help die energie veilig en nuttig te gebruiken.','Maak bewegen en sport onderdeel van het normale ritme.','Stimuleer moed, initiatief en spontaniteit.','Geef kansen om zichzelf te laten zien en uit te spreken.','Prijs inzet en steun na tegenslagen.','Actieve dans, theater of een creatieve club kan goed passen.','Laat vrienden thuis komen binnen duidelijke gezinsregels.','Help plannen en doelen voor langere termijn te onthouden.','Vermijd manipulatie, druk en emotionele chantage.','Leer doorzetten in plaats van conflicteren wanneer iets moeilijk is.']},
taurus:{title:'♉ STIER / TAURUS',tips:['Dwing delen niet af; leer het stap voor stap door voorbeeldgedrag.','Maak vroeg kennis met geld, sparen en een eenvoudig budget.','Geef meer creatieve en praktische opdrachten.','Een rustige, geduldige docent past vaak beter dan een strenge.','Vermijd schreeuwen en vernederende straffen.','Maak fijne gezinsrituelen rond eten en gezelligheid.','Kies rustige sporten met een duidelijk ritme.','Kies comfortabele kleding en prettige stoffen.','Dwing geen optreden af als het kind verlegen is.','Motiveer met duidelijke doelen en leer sparen.']},
gemini:{title:'♊ TWEELINGEN / GEMINI',tips:['Stimuleer nieuwsgierigheid en liefde voor lezen.','Maak afspraken over schermtijd in plaats van voortdurend te verbieden.','Ondersteun gezonde vriendschappen met leeftijdsgenoten.','Bied nieuwe ervaringen, uitstapjes en afwisseling.','Maak niet te veel drama van meerdere begonnen taken; leer één ding tegelijk af te ronden.','Praat veel en deel nieuws.','Introduceer vreemde talen al vroeg.','Blijf rustig bij eindeloze vragen.','Bouw vertrouwen op en blijf duidelijk de volwassene.','Stimuleer leren en oefen spreken voor een groep zonder druk.']},
cancer:{title:'♋ KREEFT / CANCER',tips:['Geef kritiek zacht en concreet, zonder vernedering.','Leg geen starre stereotypen op over hoe een kind hoort te zijn.','Praat vaak over gevoelens en leer emoties benoemen.','Kook samen en maak warme gezinsrituelen.','Creatieve activiteiten met een veilige sfeer kunnen goed passen.','Onderhoud contact met dierbare familieleden.','Laat zien dat kwetsbaarheid en om hulp vragen normaal zijn.','Leer conflicten via gesprek op te lossen.','Train het geheugen met verhalen, foto’s en associaties.','Bescherm het kind tegen vernederende of agressieve volwassenen.']},
leo:{title:'♌ LEEUW / LEO',tips:['Oprechte complimenten werken sterk motiverend.','Geef creatieve opdrachten en kansen om resultaten te laten zien.','Lees levendige verhalen en bespreek de personages.','Probeer thuis theater, rollenspellen en kleine presentaties.','Laat zelfexpressie via kleding toe binnen redelijke grenzen.','Help gezonde vriendschappen op te bouwen.','Steun interesse in video en creativiteit met regels voor digitale veiligheid.','Maak huishoudelijke taken een duidelijke verantwoordelijkheid, geen straf.','Leer omgaan met geld en aankopen plannen.','Houd een voorspelbaar dagritme.']},
virgo:{title:'♍ MAAGD / VIRGO',tips:['Een huisdier kan zorgzaamheid leren als het gezin klaar is voor die verantwoordelijkheid.','Leer stap voor stap opruimen en passende huishoudelijke taken.','Stimuleer liefde voor boeken en kennis.','Moedig interesse in natuur en observeren aan.','Geef voldoende zelfstandigheid.','Ontwikkel logisch en analytisch denken.','Zie successen, niet alleen fouten.','Leer rust nemen zonder schuldgevoel.','Laat zien hoe je problemen benoemt zonder harde kritiek.','Prijs inzet zonder de lat onhaalbaar hoog te leggen.']},
libra:{title:'♎ WEEGSCHAAL / LIBRA',tips:['Maak gezinstradities rond wandelen en samen iets doen.','Vermijd luid ruzie maken waar het kind bij is.','Partnerdans en teamactiviteiten kunnen goed passen.','Laat het kind meedenken over de inrichting van de eigen kamer.','Probeer samen tekenen, design, muziek en kunst.','Help gezond gezelschap te kiezen in plaats van status na te jagen.','Laat soms samen met een vriend leren.','Bij interesse in mode: steun veilige creatieve projecten.','Leer emoties herkennen en reguleren.','Muziek en individuele creatieve lessen kunnen goed werken.']},
scorpio:{title:'♏ SCHORPIOEN / SCORPIO',tips:['Sport, vechtsport en andere gedisciplineerde activiteiten kunnen helpen met een goede trainer.','Bied raadsels, speurwerk en puzzels aan.','Dreig nooit en gebruik geen lichamelijke straf.','Theater en acteren kunnen helpen sterke emoties te uiten.','Steun interesse in podium of modellenwerk zonder druk op uiterlijk.','Eis niet voortdurend perfecte netheid.','Laat merken dat het kind op uw steun kan rekenen.','Stimuleer gezonde ambitie en leer omgaan met verlies.','Bouw gezag op via vertrouwen en consequent gedrag, niet via angst.','Leer plannen en omgaan met geld.']},
sagittarius:{title:'♐ BOOGSCHUTTER / SAGITTARIUS',tips:['Prijs echte inzet en prestaties concreet.','Leer discipline via duidelijke regels met ruimte daarbinnen.','Steun nieuwe interesses zonder de agenda vol te proppen.','Reis en laat verschillende culturen zien wanneer dat kan.','Laat kennismaken met mensen die enthousiast en doelgericht zijn.','Paardrijden, tennis, atletiek en andere actieve sporten kunnen goed passen.','Leer hoofd- en bijzaken van elkaar te scheiden.','Maak huishoudelijke taken duidelijk en waar mogelijk interessant.','Vraag soms de mening van het kind over kleine gezinskeuzes.','Laat kleding kiezen en een eigen smaak ontwikkelen.']},
capricorn:{title:'♑ STEENBOK / CAPRICORN',tips:['Leer dag en week plannen zonder overdreven controle.','Geef een rustige, aparte plek om te leren.','Leer tijd waarderen via routine, niet door voortdurend te haasten.','Respecteer een eigen mening en bespreek verschillen rustig.','Vergelijk niet met andere kinderen.','Bouw de relatie op vertrouwen, eerlijkheid en rechtvaardigheid.','Steun interesse in technologie, projecten en ondernemerschap.','Bewaar regelmaat in eten, rust en bewegen.','Zoek een sterke omgeving zonder status als doel te maken.','Sla lange preken over; wees kort en concreet.']},
aquarius:{title:'♒ WATERMAN / AQUARIUS',tips:['Uitstapjes en nieuwe plaatsen verbreden de blik.','Ondersteun vriendschappen en sociale contacten.','Zoek docenten die leerstof verbinden met de moderne wereld.','Ontwikkel kritisch denken en feiten controleren.','Gebruik discipline als steunende structuur, niet als onderdrukking van vrijheid.','Bezoek wetenschapsmusea, planetaria en leerzame activiteiten.','Respecteer persoonlijke grenzen en dwing lichamelijke affectie niet af.','Laat veilig experimenteren met persoonlijke stijl.','Vermijd omgevingen waar individualiteit voortdurend wordt onderdrukt.','Kies gadgets op nut, niet alleen omdat ze trendy zijn.']},
pisces:{title:'♓ VISSEN / PISCES',tips:['Laat kennismaken met kunst, tentoonstellingen en creatieve activiteiten.','Kies comfortabele, mooie kleding zonder merken als maatstaf voor waarde te gebruiken.','Stimuleer liefde voor natuur en dieren.','Zorg voor voldoende rust en stille tijd.','Bouw gezonde gewoonten op zonder overmatige controle.','Leer emoties gezond te uiten en om steun te vragen.','Muziek, zingen en creatieve activiteiten kunnen goed passen.','Lees verhalen en stimuleer fantasie.','Vraag na school rustig naar gevoelens en relaties met anderen.','Poëzie, theater en andere creatieve vormen van zelfexpressie kunnen helpen.']}
}
};
const tipsData=Object.fromEntries(Object.keys(tipsTranslations.ru).map(sign=>[sign,{
get title(){return (tipsTranslations[currentLanguage]||tipsTranslations.nl)[sign].title;},
get tips(){return (tipsTranslations[currentLanguage]||tipsTranslations.nl)[sign].tips;}
}]));